fernetKey: cjVBRzlrdm9XR0NOSUhtM2NHTnRST0U3RmxHNEQ4bTc=
webserverSecretKey: cjVBRzlrdm9XR0NOSUhtM2NHTnRST0U3RmxHNEQ4bTc=
executor: "KubernetesExecutor"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/harshitgurani/kubernetes_de.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"